[package]
name = "explorer-mem-leak"
version = "0.1.0"
authors = ["Naughty <dorminsama@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = "3.2.1"
sysinfo = "0.15.3"

[dependencies.core_extensions]
version = "1.5"
features = [
    "integers"
]
